services:
  web:
    build: .
    container_name: TicketSystem
    ports: 
    - "8000:8000"
    volumes:
      - .:/app
      - django_media:/app/media
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py createsuperuser --noinput || true && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: django_postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD} 
    ports:
      - "5432:5432"
    volumes:
      - pg_data_secure:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DjangoFastAPI"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data_secure:
  django_media:
