version: '3.8'

services:
  db:
    image: postgres:15
    container_name: django_postgres_db
    environment:
      POSTGRES_DB: DjangoFastAPI
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg_data_secure:/var/lib/postgresql/data 

volumes:
  pg_data_secure: # Docker будет вечно хранить эту папку на ПК
